<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageVersion Include="MahApps.Metro" Version="2.4.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.0" />
    <PackageVersion Include="SQLitePCLRaw.core" Version="3.0.0" />
    <PackageVersion Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.50.3" />
    <PackageVersion Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="3.0.0" />
    <PackageVersion Include="Zeroconf" Version="3.7.16" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>