<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LlrpReaderStudio.Core\LlrpReaderStudio.Core.csproj" />
    <ProjectReference Include="..\LlrpReaderStudio.Infrastructure\LlrpReaderStudio.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="FontAwesome.Sharp" />
    <PackageReference Include="MahApps.Metro" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
  </ItemGroup>
</Project>
