<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LlrpReaderStudio.Core\LlrpReaderStudio.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LlrpSdk" />
    <PackageReference Include="LlrpSdk.Extensions.Impinj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Zeroconf" />
  </ItemGroup>
</Project>
